"use client"

import { useState } from "react"
// Import directly from the component files to avoid any path issues
import { TipTapEditor } from "@/components/TipTapEditor/TipTapEditor"
import { SimplifiedEditor } from "@/components/SimplifiedEditor/SimplifiedEditor"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export default function Home() {
  const [fullEditorContent, setFullEditorContent] = useState("<p>Start typing in the full-featured editor...</p>")
  const [simpleEditorContent, setSimpleEditorContent] = useState("")

  return (
    <main className="container mx-auto py-10 space-y-10 px-4">
      <div className="text-center mb-10">
        <h1 className="text-4xl font-bold tracking-tight">TipTap Editor Examples</h1>
        <p className="text-lg text-muted-foreground mt-2">
          Two variations of rich text editors built with TipTap and React
        </p>
      </div>

      <Tabs defaultValue="both" className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="both">Both Editors</TabsTrigger>
          <TabsTrigger value="full">Full Editor</TabsTrigger>
          <TabsTrigger value="simple">Simple Editor</TabsTrigger>
        </TabsList>

        <TabsContent value="both" className="space-y-8 mt-6 w-full">
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Simplified Editor</CardTitle>
              <CardDescription>A lightweight editor with just the essential formatting options</CardDescription>
            </CardHeader>
            <CardContent className="w-full p-0">
              <SimplifiedEditor onUpdate={(html) => setSimpleEditorContent(html)} content={simpleEditorContent} />
            </CardContent>
          </Card>

          <Card className="w-full">
            <CardHeader>
              <CardTitle>Full-Featured Editor</CardTitle>
              <CardDescription>A comprehensive rich text editor with advanced formatting options</CardDescription>
            </CardHeader>
            <CardContent className="w-full p-0">
              <TipTapEditor onUpdate={(html) => setFullEditorContent(html)} content={fullEditorContent} />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="full" className="mt-6 w-full">
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Full-Featured Editor</CardTitle>
              <CardDescription>A comprehensive rich text editor with advanced formatting options</CardDescription>
            </CardHeader>
            <CardContent className="w-full p-0">
              <TipTapEditor onUpdate={(html) => setFullEditorContent(html)} content={fullEditorContent} />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="simple" className="mt-6 w-full">
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Simplified Editor</CardTitle>
              <CardDescription>A lightweight editor with just the essential formatting options</CardDescription>
            </CardHeader>
            <CardContent className="w-full p-0">
              <SimplifiedEditor onUpdate={(html) => setSimpleEditorContent(html)} content={simpleEditorContent} />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-10">
        <Card>
          <CardHeader>
            <CardTitle>Simple Editor Output</CardTitle>
            <CardDescription>HTML generated by the simplified editor</CardDescription>
          </CardHeader>
          <CardContent>
            <pre className="bg-muted p-4 rounded-md overflow-auto text-sm">
              {simpleEditorContent || "<No content yet>"}
            </pre>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Full Editor Output</CardTitle>
            <CardDescription>HTML generated by the full-featured editor</CardDescription>
          </CardHeader>
          <CardContent>
            <pre className="bg-muted p-4 rounded-md overflow-auto text-sm">
              {fullEditorContent || "<No content yet>"}
            </pre>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
